version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo
    working_directory: /var/www/project
    steps:
      - checkout

      # Load git submodules
      - run:
          name: "Load git submodules"
          command: git submodule sync && git submodule update --init

      # Build compiled sites
      - run:
          name: "Build English and French sites"
          command: |
            hugo -d ~/cds-website
            chmod -R 755 ~/cds-website

      # Store compiled cache (persisted across jobs)
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: cds-website-dist-{{ checksum ".circle-sha" }}
          paths:
            ~/cds-website
      - run:
          name: "Create archive"
          command: |
            cd ~
            tar -czvf cds-website.tar.gz ~/cds-website
      - store_artifacts:
          path: ~/cds-website.tar.gz
          destination: cds-website.tar.gz

  test:
    docker:
      - image: cibuilds/hugo
    steps:
      # Restore compiled cache (persisted across jobs)
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - cds-website-dist-{{ checksum ".circle-sha" }}

      - run:
          name: "Test English"
          command: htmlproofer ~/cds-website/en --allow-hash-href --empty_alt_ignore --check-favicon --check-html --disable-external --file-ignore=/lib/,/admin/

      - run:
          name: "Test French"
          command: htmlproofer ~/cds-website/fr --allow-hash-href --empty_alt_ignore --check-favicon --check-html --disable-external --file-ignore=/lib/,/admin/

  deploy:
    docker:
      - image: cdssnc/aws-cli
    steps:
      # Configure AWS CLI
      - run:
          name: "Configure AWS Cli"
          command: |
            aws configure set preview.cloudfront true
            aws configure set preview.create-invalidation true

      # Restore compiled cache (persisted across jobs)
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - cds-website-dist-{{ checksum ".circle-sha" }}

      # Deploy english from cache and create Cloudfront object invalidation
      - deploy:
          name: "Deploy English"
          command: |
            # aws s3 sync /home/circleci/cds-website/en s3://cds-website-english/ --delete
            # aws cloudfront create-invalidation --cli-input-json "{\"DistributionId\":\"E3EIUBOL3WTOOO\",\"InvalidationBatch\":{\"Paths\":{\"Quantity\":1,\"Items\":[\"/*\"]},\"CallerReference\":\"$(date +%s)\"}}"

      # Deploy french from cache and create Cloudfront object invalidation
      # - deploy:
          # name: "Deploy French"
          # command: |
            # aws s3 sync /home/circleci/snc-website s3://cds-website-french/ --delete
            # aws cloudfront create-invalidation --cli-input-json "{\"DistributionId\":\"E3FI5UW2E5PBD3\",\"InvalidationBatch\":{\"Paths\":{\"Quantity\":1,\"Items\":[\"/*\"]},\"CallerReference\":\"$(date +%s)\"}}"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      # - deploy:
      #    requires:
      #      - build
            # - test
      #    filters:
      #      branches:
      #        only: ci_cd_config
