backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: cds-snc/website-reboot
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/en/blog/posts"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "TranslationKey", name: "translationKey", widget: "string"}
  - name: "blogue"
    label: "Blogue"
    folder: "content/fr/blog/posts"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "TranslationKey", name: "translationKey", widget: "string"}

exclude:
 - admin/index.js
 - webpack.config.js
 - package.json
 - README.md
 - node_modules/